steps:
- uses: actions/checkout@v2
- uses: actions/setup-go@v2
  with:
    go-version: '^1.16.3'
- uses: supercharge/redis-github-action@1.2.0
  with:
    redis-version: ${{ matrix.redis-version }}
- run: go test -v -race ./
