name: Run Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.3'
    - uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: 6
    - run: go test -v -race ./
